#pragma once

#include "NativeGameplayTags.h"

namespace DCGameplayTags
{
	// Native Input
	DREAMCATCHER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Move);
	DREAMCATCHER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look);

	// Ability Input
	DREAMCATCHER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Jump);
	DREAMCATCHER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Aim);
	DREAMCATCHER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Dodge);
	DREAMCATCHER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Ultimate);
	DREAMCATCHER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Weapon_Fire);
	DREAMCATCHER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Weapon_Reload);

	// Ability
	DREAMCATCHER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Action_Aim);
	DREAMCATCHER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Action_Dodge);
	DREAMCATCHER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Action_Ultimate);
	DREAMCATCHER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Action_WeaponFire);
	DREAMCATCHER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Action_Reload);
	DREAMCATCHER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Action_Death);

	// State
	DREAMCATCHER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Aim_Shoulder);
	DREAMCATCHER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Aim_Scope);
	DREAMCATCHER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Dodging);
	DREAMCATCHER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Firing);
	DREAMCATCHER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Reloading);
	DREAMCATCHER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Dead);
	DREAMCATCHER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Attack_Intent);
	DREAMCATCHER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Attack_Windup);
	DREAMCATCHER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Attack_Active);
	DREAMCATCHER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Attack_Recovery);

	// Gameplay
	DREAMCATCHER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Gameplay_DamageImmunity);
	DREAMCATCHER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Gameplay_AbilityInputBlocked);

	// Event
	DREAMCATCHER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Death);
	DREAMCATCHER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Dodge_Success);

	// Cooldown
	DREAMCATCHER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown_Dodge);
	DREAMCATCHER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown_Ultimate);
}